# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, variable: $(Build.ArtifactStagingDirectory) and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '16'
  displayName: 'Install node'

- script: |
    node txt/SimpleFileCreator.js


- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '*.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'message.txt'
    publishLocation: 'Container'
