# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pwd
  displayName: 'Shows current location'


- script: |
    echo Hello $(firstName) $(lastName) your age is: $(age) macro syntax
  displayName: 'display variables with macro syntax'

- script: |
    echo Hello ${{variables.firstName}} ${{variables.lastName}} your age is: ${{variables.age}} macro syntax
  displayName: 'display variables with template expression syntax'


- script: |
    echo Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)
    echo System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Run a multi-line script'

- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '16'
  displayName: 'Install node'

- script: |
    node SimpleFileCreator.js $(FIRSTNAME) $(LASTNAME) $(AGE)


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '*.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'message.txt'
    publishLocation: 'Container'
